### ISSUE TITLE
Rating type overlaps with scores when level names are long

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#1]
### Page

Search

### Bug description

```bash
1. Click Top Demons.
2. See that some rating types overlap with scores.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191270791-ef76874e-6bcd-4cba-bdc2-24a62a91f825.png)

**Comment by naoei** [comment]
Would you agree that the better solution would be to place the rating type above the level name?

**Comment by vipringd** [comment]
No, it looks good with rating types on the right side of the level name. When the level name is above a certain amount of characters, the text size can be scaled down.

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
