### ISSUE TITLE
Too big spacing below the header

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#2]
### Page

Other

### Bug description

```bash
1. This is seen at the top of the website on every page.
2.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191271222-121bcfcd-c98d-43a8-97bf-7e22dc054388.png)

**Comment by naoei** [comment]
This is only to give headroom for users and in my personal opinion, perfectly fine UX. Can you provide any reasons as to why we shouldn't have this?

**Comment by vipringd** [comment]
Reason: It looks bad. I just checked all the websites I use daily, and I can't seem to find any that have a random big empty space at the top.

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
