### ISSUE TITLE
Incorrect order and capitalization on Search and Top Demons

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#4]
### Page

Search

### Bug description

```bash
1. "Search demons..." should be "Search Demons"
2. Sort by Overall by default, not Difficulty.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191271635-eccc5d94-50c0-410b-966b-026bdbed0652.png)

**Comment by naoei** [comment]
By default, all searches are sorted by overall.

**Comment by vipringd** [comment]
Top Demons is sorted by Difficulty by default right now. You can see this by Tartarus being first place. It's supposed to be sorted by Overall by default. This is not about searching.

**Comment by naoei** [comment]
This issue you presented will be resolved in the next hotfix release.
