### ISSUE TITLE
Fix Login text a little

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#6]
### Page

User

### Bug description

```bash
1. Remove "some smart thing here idk lol". You can remove that line and space completely. 
2.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191272007-4209f698-6cc6-4bec-a9fa-b7d0d821118e.png)

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
