### ISSUE TITLE
Change some spelling on the Register pages

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#7]
### Page

User

### Bug description

```bash
1. "Please don't use the same password from GD." -> "Please don't use the same password as in-game."
2. GD -> Geometry Dash both places on the Verification page.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191272167-5b37bd33-1875-41af-aefe-7d154c538bc8.png)
![unknown](https://user-images.githubusercontent.com/70018202/191272185-b694e1a8-2988-4cb4-b854-d50b94b224ad.png)

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
