### ISSUE TITLE
Sort by Overall by default on Home, not Difficulty

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#8]
### Page

Home

### Bug description

```bash
1. Change from Difficulty to Overall for default sorting.
2. You could remove "Diff. ..." completely if you want to fully spell out "Overall: ..." since that's all that matters here.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191272508-83134dea-8617-42e8-98df-cda31c90affb.png)

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
