### ISSUE TITLE
Some letters cut off on Search

### ISSUE THREAD

**Issue by vipringd** [MyDemonList/mdl-issue-tracker#9]
### Page

Search

### Bug description

```bash
1. Letters that go far down cut off a little in level names, like the "g" in Espionage.
2.
3.
...
```

### Screenshots or videos

![unknown](https://user-images.githubusercontent.com/70018202/191272729-8c9d9856-7775-42a1-a0da-08a84f729b82.png)

**Comment by naoei** [comment]
Thank you for your feedback. The issue you presented will be resolved in the next hotfix release.
